// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/externalusermapping"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ExternalUserMapping is the model entity for the ExternalUserMapping schema.
type ExternalUserMapping struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// ExternalUserID holds the value of the "external_user_id" field.
	ExternalUserID string `json:"external_user_id,omitempty"`
	// ExternalOrganizationID holds the value of the "external_organization_id" field.
	ExternalOrganizationID string `json:"external_organization_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// UsernameSnapshot holds the value of the "username_snapshot" field.
	UsernameSnapshot string `json:"username_snapshot,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ExternalUserMappingQuery when eager-loading is set.
	Edges        ExternalUserMappingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ExternalUserMappingEdges holds the relations/edges for other nodes in the graph.
type ExternalUserMappingEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ExternalUserMappingEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ExternalUserMappingEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExternalUserMapping) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case externalusermapping.FieldID, externalusermapping.FieldUserID, externalusermapping.FieldAPIKeyID:
			values[i] = new(sql.NullInt64)
		case externalusermapping.FieldExternalUserID, externalusermapping.FieldExternalOrganizationID, externalusermapping.FieldUsernameSnapshot:
			values[i] = new(sql.NullString)
		case externalusermapping.FieldCreatedAt, externalusermapping.FieldUpdatedAt, externalusermapping.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExternalUserMapping fields.
func (_m *ExternalUserMapping) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case externalusermapping.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case externalusermapping.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case externalusermapping.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case externalusermapping.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case externalusermapping.FieldExternalUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_user_id", values[i])
			} else if value.Valid {
				_m.ExternalUserID = value.String
			}
		case externalusermapping.FieldExternalOrganizationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_organization_id", values[i])
			} else if value.Valid {
				_m.ExternalOrganizationID = value.String
			}
		case externalusermapping.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case externalusermapping.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case externalusermapping.FieldUsernameSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username_snapshot", values[i])
			} else if value.Valid {
				_m.UsernameSnapshot = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExternalUserMapping.
// This includes values selected through modifiers, order, etc.
func (_m *ExternalUserMapping) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ExternalUserMapping entity.
func (_m *ExternalUserMapping) QueryUser() *UserQuery {
	return NewExternalUserMappingClient(_m.config).QueryUser(_m)
}

// QueryAPIKey queries the "api_key" edge of the ExternalUserMapping entity.
func (_m *ExternalUserMapping) QueryAPIKey() *APIKeyQuery {
	return NewExternalUserMappingClient(_m.config).QueryAPIKey(_m)
}

// Update returns a builder for updating this ExternalUserMapping.
// Note that you need to call ExternalUserMapping.Unwrap() before calling this method if this ExternalUserMapping
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ExternalUserMapping) Update() *ExternalUserMappingUpdateOne {
	return NewExternalUserMappingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ExternalUserMapping entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ExternalUserMapping) Unwrap() *ExternalUserMapping {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExternalUserMapping is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ExternalUserMapping) String() string {
	var builder strings.Builder
	builder.WriteString("ExternalUserMapping(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("external_user_id=")
	builder.WriteString(_m.ExternalUserID)
	builder.WriteString(", ")
	builder.WriteString("external_organization_id=")
	builder.WriteString(_m.ExternalOrganizationID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("username_snapshot=")
	builder.WriteString(_m.UsernameSnapshot)
	builder.WriteByte(')')
	return builder.String()
}

// ExternalUserMappings is a parsable slice of ExternalUserMapping.
type ExternalUserMappings []*ExternalUserMapping
