// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/externalusermapping"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ExternalUserMappingUpdate is the builder for updating ExternalUserMapping entities.
type ExternalUserMappingUpdate struct {
	config
	hooks    []Hook
	mutation *ExternalUserMappingMutation
}

// Where appends a list predicates to the ExternalUserMappingUpdate builder.
func (_u *ExternalUserMappingUpdate) Where(ps ...predicate.ExternalUserMapping) *ExternalUserMappingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExternalUserMappingUpdate) SetUpdatedAt(v time.Time) *ExternalUserMappingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ExternalUserMappingUpdate) SetDeletedAt(v time.Time) *ExternalUserMappingUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ExternalUserMappingUpdate) SetNillableDeletedAt(v *time.Time) *ExternalUserMappingUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ExternalUserMappingUpdate) ClearDeletedAt() *ExternalUserMappingUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetExternalUserID sets the "external_user_id" field.
func (_u *ExternalUserMappingUpdate) SetExternalUserID(v string) *ExternalUserMappingUpdate {
	_u.mutation.SetExternalUserID(v)
	return _u
}

// SetNillableExternalUserID sets the "external_user_id" field if the given value is not nil.
func (_u *ExternalUserMappingUpdate) SetNillableExternalUserID(v *string) *ExternalUserMappingUpdate {
	if v != nil {
		_u.SetExternalUserID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ExternalUserMappingUpdate) SetUserID(v int64) *ExternalUserMappingUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ExternalUserMappingUpdate) SetNillableUserID(v *int64) *ExternalUserMappingUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *ExternalUserMappingUpdate) SetAPIKeyID(v int64) *ExternalUserMappingUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *ExternalUserMappingUpdate) SetNillableAPIKeyID(v *int64) *ExternalUserMappingUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetUsernameSnapshot sets the "username_snapshot" field.
func (_u *ExternalUserMappingUpdate) SetUsernameSnapshot(v string) *ExternalUserMappingUpdate {
	_u.mutation.SetUsernameSnapshot(v)
	return _u
}

// SetNillableUsernameSnapshot sets the "username_snapshot" field if the given value is not nil.
func (_u *ExternalUserMappingUpdate) SetNillableUsernameSnapshot(v *string) *ExternalUserMappingUpdate {
	if v != nil {
		_u.SetUsernameSnapshot(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ExternalUserMappingUpdate) SetUser(v *User) *ExternalUserMappingUpdate {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *ExternalUserMappingUpdate) SetAPIKey(v *APIKey) *ExternalUserMappingUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the ExternalUserMappingMutation object of the builder.
func (_u *ExternalUserMappingUpdate) Mutation() *ExternalUserMappingMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ExternalUserMappingUpdate) ClearUser() *ExternalUserMappingUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *ExternalUserMappingUpdate) ClearAPIKey() *ExternalUserMappingUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExternalUserMappingUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExternalUserMappingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExternalUserMappingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExternalUserMappingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExternalUserMappingUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if externalusermapping.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized externalusermapping.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := externalusermapping.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExternalUserMappingUpdate) check() error {
	if v, ok := _u.mutation.ExternalUserID(); ok {
		if err := externalusermapping.ExternalUserIDValidator(v); err != nil {
			return &ValidationError{Name: "external_user_id", err: fmt.Errorf(`ent: validator failed for field "ExternalUserMapping.external_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UsernameSnapshot(); ok {
		if err := externalusermapping.UsernameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "username_snapshot", err: fmt.Errorf(`ent: validator failed for field "ExternalUserMapping.username_snapshot": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ExternalUserMapping.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ExternalUserMapping.api_key"`)
	}
	return nil
}

func (_u *ExternalUserMappingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(externalusermapping.Table, externalusermapping.Columns, sqlgraph.NewFieldSpec(externalusermapping.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(externalusermapping.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(externalusermapping.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(externalusermapping.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExternalUserID(); ok {
		_spec.SetField(externalusermapping.FieldExternalUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsernameSnapshot(); ok {
		_spec.SetField(externalusermapping.FieldUsernameSnapshot, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   externalusermapping.UserTable,
			Columns: []string{externalusermapping.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   externalusermapping.UserTable,
			Columns: []string{externalusermapping.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   externalusermapping.APIKeyTable,
			Columns: []string{externalusermapping.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   externalusermapping.APIKeyTable,
			Columns: []string{externalusermapping.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{externalusermapping.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExternalUserMappingUpdateOne is the builder for updating a single ExternalUserMapping entity.
type ExternalUserMappingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExternalUserMappingMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExternalUserMappingUpdateOne) SetUpdatedAt(v time.Time) *ExternalUserMappingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ExternalUserMappingUpdateOne) SetDeletedAt(v time.Time) *ExternalUserMappingUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ExternalUserMappingUpdateOne) SetNillableDeletedAt(v *time.Time) *ExternalUserMappingUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ExternalUserMappingUpdateOne) ClearDeletedAt() *ExternalUserMappingUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetExternalUserID sets the "external_user_id" field.
func (_u *ExternalUserMappingUpdateOne) SetExternalUserID(v string) *ExternalUserMappingUpdateOne {
	_u.mutation.SetExternalUserID(v)
	return _u
}

// SetNillableExternalUserID sets the "external_user_id" field if the given value is not nil.
func (_u *ExternalUserMappingUpdateOne) SetNillableExternalUserID(v *string) *ExternalUserMappingUpdateOne {
	if v != nil {
		_u.SetExternalUserID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ExternalUserMappingUpdateOne) SetUserID(v int64) *ExternalUserMappingUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ExternalUserMappingUpdateOne) SetNillableUserID(v *int64) *ExternalUserMappingUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *ExternalUserMappingUpdateOne) SetAPIKeyID(v int64) *ExternalUserMappingUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *ExternalUserMappingUpdateOne) SetNillableAPIKeyID(v *int64) *ExternalUserMappingUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetUsernameSnapshot sets the "username_snapshot" field.
func (_u *ExternalUserMappingUpdateOne) SetUsernameSnapshot(v string) *ExternalUserMappingUpdateOne {
	_u.mutation.SetUsernameSnapshot(v)
	return _u
}

// SetNillableUsernameSnapshot sets the "username_snapshot" field if the given value is not nil.
func (_u *ExternalUserMappingUpdateOne) SetNillableUsernameSnapshot(v *string) *ExternalUserMappingUpdateOne {
	if v != nil {
		_u.SetUsernameSnapshot(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ExternalUserMappingUpdateOne) SetUser(v *User) *ExternalUserMappingUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *ExternalUserMappingUpdateOne) SetAPIKey(v *APIKey) *ExternalUserMappingUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the ExternalUserMappingMutation object of the builder.
func (_u *ExternalUserMappingUpdateOne) Mutation() *ExternalUserMappingMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ExternalUserMappingUpdateOne) ClearUser() *ExternalUserMappingUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *ExternalUserMappingUpdateOne) ClearAPIKey() *ExternalUserMappingUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// Where appends a list predicates to the ExternalUserMappingUpdate builder.
func (_u *ExternalUserMappingUpdateOne) Where(ps ...predicate.ExternalUserMapping) *ExternalUserMappingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExternalUserMappingUpdateOne) Select(field string, fields ...string) *ExternalUserMappingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ExternalUserMapping entity.
func (_u *ExternalUserMappingUpdateOne) Save(ctx context.Context) (*ExternalUserMapping, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExternalUserMappingUpdateOne) SaveX(ctx context.Context) *ExternalUserMapping {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExternalUserMappingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExternalUserMappingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExternalUserMappingUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if externalusermapping.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized externalusermapping.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := externalusermapping.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExternalUserMappingUpdateOne) check() error {
	if v, ok := _u.mutation.ExternalUserID(); ok {
		if err := externalusermapping.ExternalUserIDValidator(v); err != nil {
			return &ValidationError{Name: "external_user_id", err: fmt.Errorf(`ent: validator failed for field "ExternalUserMapping.external_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UsernameSnapshot(); ok {
		if err := externalusermapping.UsernameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "username_snapshot", err: fmt.Errorf(`ent: validator failed for field "ExternalUserMapping.username_snapshot": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ExternalUserMapping.user"`)
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ExternalUserMapping.api_key"`)
	}
	return nil
}

func (_u *ExternalUserMappingUpdateOne) sqlSave(ctx context.Context) (_node *ExternalUserMapping, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(externalusermapping.Table, externalusermapping.Columns, sqlgraph.NewFieldSpec(externalusermapping.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ExternalUserMapping.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, externalusermapping.FieldID)
		for _, f := range fields {
			if !externalusermapping.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != externalusermapping.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(externalusermapping.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(externalusermapping.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(externalusermapping.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExternalUserID(); ok {
		_spec.SetField(externalusermapping.FieldExternalUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsernameSnapshot(); ok {
		_spec.SetField(externalusermapping.FieldUsernameSnapshot, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   externalusermapping.UserTable,
			Columns: []string{externalusermapping.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   externalusermapping.UserTable,
			Columns: []string{externalusermapping.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   externalusermapping.APIKeyTable,
			Columns: []string{externalusermapping.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   externalusermapping.APIKeyTable,
			Columns: []string{externalusermapping.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ExternalUserMapping{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{externalusermapping.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
