// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/externalusermapping"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ExternalUserMappingCreate is the builder for creating a ExternalUserMapping entity.
type ExternalUserMappingCreate struct {
	config
	mutation *ExternalUserMappingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExternalUserMappingCreate) SetCreatedAt(v time.Time) *ExternalUserMappingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExternalUserMappingCreate) SetNillableCreatedAt(v *time.Time) *ExternalUserMappingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExternalUserMappingCreate) SetUpdatedAt(v time.Time) *ExternalUserMappingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExternalUserMappingCreate) SetNillableUpdatedAt(v *time.Time) *ExternalUserMappingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ExternalUserMappingCreate) SetDeletedAt(v time.Time) *ExternalUserMappingCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ExternalUserMappingCreate) SetNillableDeletedAt(v *time.Time) *ExternalUserMappingCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetExternalUserID sets the "external_user_id" field.
func (_c *ExternalUserMappingCreate) SetExternalUserID(v string) *ExternalUserMappingCreate {
	_c.mutation.SetExternalUserID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ExternalUserMappingCreate) SetUserID(v int64) *ExternalUserMappingCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *ExternalUserMappingCreate) SetAPIKeyID(v int64) *ExternalUserMappingCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetUsernameSnapshot sets the "username_snapshot" field.
func (_c *ExternalUserMappingCreate) SetUsernameSnapshot(v string) *ExternalUserMappingCreate {
	_c.mutation.SetUsernameSnapshot(v)
	return _c
}

// SetNillableUsernameSnapshot sets the "username_snapshot" field if the given value is not nil.
func (_c *ExternalUserMappingCreate) SetNillableUsernameSnapshot(v *string) *ExternalUserMappingCreate {
	if v != nil {
		_c.SetUsernameSnapshot(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ExternalUserMappingCreate) SetUser(v *User) *ExternalUserMappingCreate {
	return _c.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *ExternalUserMappingCreate) SetAPIKey(v *APIKey) *ExternalUserMappingCreate {
	return _c.SetAPIKeyID(v.ID)
}

// Mutation returns the ExternalUserMappingMutation object of the builder.
func (_c *ExternalUserMappingCreate) Mutation() *ExternalUserMappingMutation {
	return _c.mutation
}

// Save creates the ExternalUserMapping in the database.
func (_c *ExternalUserMappingCreate) Save(ctx context.Context) (*ExternalUserMapping, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExternalUserMappingCreate) SaveX(ctx context.Context) *ExternalUserMapping {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExternalUserMappingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExternalUserMappingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExternalUserMappingCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if externalusermapping.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized externalusermapping.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := externalusermapping.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if externalusermapping.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized externalusermapping.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := externalusermapping.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.UsernameSnapshot(); !ok {
		v := externalusermapping.DefaultUsernameSnapshot
		_c.mutation.SetUsernameSnapshot(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExternalUserMappingCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ExternalUserMapping.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ExternalUserMapping.updated_at"`)}
	}
	if _, ok := _c.mutation.ExternalUserID(); !ok {
		return &ValidationError{Name: "external_user_id", err: errors.New(`ent: missing required field "ExternalUserMapping.external_user_id"`)}
	}
	if v, ok := _c.mutation.ExternalUserID(); ok {
		if err := externalusermapping.ExternalUserIDValidator(v); err != nil {
			return &ValidationError{Name: "external_user_id", err: fmt.Errorf(`ent: validator failed for field "ExternalUserMapping.external_user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ExternalUserMapping.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "ExternalUserMapping.api_key_id"`)}
	}
	if _, ok := _c.mutation.UsernameSnapshot(); !ok {
		return &ValidationError{Name: "username_snapshot", err: errors.New(`ent: missing required field "ExternalUserMapping.username_snapshot"`)}
	}
	if v, ok := _c.mutation.UsernameSnapshot(); ok {
		if err := externalusermapping.UsernameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "username_snapshot", err: fmt.Errorf(`ent: validator failed for field "ExternalUserMapping.username_snapshot": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ExternalUserMapping.user"`)}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "ExternalUserMapping.api_key"`)}
	}
	return nil
}

func (_c *ExternalUserMappingCreate) sqlSave(ctx context.Context) (*ExternalUserMapping, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExternalUserMappingCreate) createSpec() (*ExternalUserMapping, *sqlgraph.CreateSpec) {
	var (
		_node = &ExternalUserMapping{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(externalusermapping.Table, sqlgraph.NewFieldSpec(externalusermapping.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(externalusermapping.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(externalusermapping.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(externalusermapping.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.ExternalUserID(); ok {
		_spec.SetField(externalusermapping.FieldExternalUserID, field.TypeString, value)
		_node.ExternalUserID = value
	}
	if value, ok := _c.mutation.UsernameSnapshot(); ok {
		_spec.SetField(externalusermapping.FieldUsernameSnapshot, field.TypeString, value)
		_node.UsernameSnapshot = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   externalusermapping.UserTable,
			Columns: []string{externalusermapping.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   externalusermapping.APIKeyTable,
			Columns: []string{externalusermapping.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExternalUserMapping.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExternalUserMappingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ExternalUserMappingCreate) OnConflict(opts ...sql.ConflictOption) *ExternalUserMappingUpsertOne {
	_c.conflict = opts
	return &ExternalUserMappingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExternalUserMapping.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExternalUserMappingCreate) OnConflictColumns(columns ...string) *ExternalUserMappingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExternalUserMappingUpsertOne{
		create: _c,
	}
}

type (
	// ExternalUserMappingUpsertOne is the builder for "upsert"-ing
	//  one ExternalUserMapping node.
	ExternalUserMappingUpsertOne struct {
		create *ExternalUserMappingCreate
	}

	// ExternalUserMappingUpsert is the "OnConflict" setter.
	ExternalUserMappingUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ExternalUserMappingUpsert) SetUpdatedAt(v time.Time) *ExternalUserMappingUpsert {
	u.Set(externalusermapping.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExternalUserMappingUpsert) UpdateUpdatedAt() *ExternalUserMappingUpsert {
	u.SetExcluded(externalusermapping.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ExternalUserMappingUpsert) SetDeletedAt(v time.Time) *ExternalUserMappingUpsert {
	u.Set(externalusermapping.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ExternalUserMappingUpsert) UpdateDeletedAt() *ExternalUserMappingUpsert {
	u.SetExcluded(externalusermapping.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ExternalUserMappingUpsert) ClearDeletedAt() *ExternalUserMappingUpsert {
	u.SetNull(externalusermapping.FieldDeletedAt)
	return u
}

// SetExternalUserID sets the "external_user_id" field.
func (u *ExternalUserMappingUpsert) SetExternalUserID(v string) *ExternalUserMappingUpsert {
	u.Set(externalusermapping.FieldExternalUserID, v)
	return u
}

// UpdateExternalUserID sets the "external_user_id" field to the value that was provided on create.
func (u *ExternalUserMappingUpsert) UpdateExternalUserID() *ExternalUserMappingUpsert {
	u.SetExcluded(externalusermapping.FieldExternalUserID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ExternalUserMappingUpsert) SetUserID(v int64) *ExternalUserMappingUpsert {
	u.Set(externalusermapping.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ExternalUserMappingUpsert) UpdateUserID() *ExternalUserMappingUpsert {
	u.SetExcluded(externalusermapping.FieldUserID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ExternalUserMappingUpsert) SetAPIKeyID(v int64) *ExternalUserMappingUpsert {
	u.Set(externalusermapping.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ExternalUserMappingUpsert) UpdateAPIKeyID() *ExternalUserMappingUpsert {
	u.SetExcluded(externalusermapping.FieldAPIKeyID)
	return u
}

// SetUsernameSnapshot sets the "username_snapshot" field.
func (u *ExternalUserMappingUpsert) SetUsernameSnapshot(v string) *ExternalUserMappingUpsert {
	u.Set(externalusermapping.FieldUsernameSnapshot, v)
	return u
}

// UpdateUsernameSnapshot sets the "username_snapshot" field to the value that was provided on create.
func (u *ExternalUserMappingUpsert) UpdateUsernameSnapshot() *ExternalUserMappingUpsert {
	u.SetExcluded(externalusermapping.FieldUsernameSnapshot)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ExternalUserMapping.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ExternalUserMappingUpsertOne) UpdateNewValues() *ExternalUserMappingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(externalusermapping.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExternalUserMapping.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExternalUserMappingUpsertOne) Ignore() *ExternalUserMappingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExternalUserMappingUpsertOne) DoNothing() *ExternalUserMappingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExternalUserMappingCreate.OnConflict
// documentation for more info.
func (u *ExternalUserMappingUpsertOne) Update(set func(*ExternalUserMappingUpsert)) *ExternalUserMappingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExternalUserMappingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExternalUserMappingUpsertOne) SetUpdatedAt(v time.Time) *ExternalUserMappingUpsertOne {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExternalUserMappingUpsertOne) UpdateUpdatedAt() *ExternalUserMappingUpsertOne {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ExternalUserMappingUpsertOne) SetDeletedAt(v time.Time) *ExternalUserMappingUpsertOne {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ExternalUserMappingUpsertOne) UpdateDeletedAt() *ExternalUserMappingUpsertOne {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ExternalUserMappingUpsertOne) ClearDeletedAt() *ExternalUserMappingUpsertOne {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.ClearDeletedAt()
	})
}

// SetExternalUserID sets the "external_user_id" field.
func (u *ExternalUserMappingUpsertOne) SetExternalUserID(v string) *ExternalUserMappingUpsertOne {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.SetExternalUserID(v)
	})
}

// UpdateExternalUserID sets the "external_user_id" field to the value that was provided on create.
func (u *ExternalUserMappingUpsertOne) UpdateExternalUserID() *ExternalUserMappingUpsertOne {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.UpdateExternalUserID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ExternalUserMappingUpsertOne) SetUserID(v int64) *ExternalUserMappingUpsertOne {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ExternalUserMappingUpsertOne) UpdateUserID() *ExternalUserMappingUpsertOne {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ExternalUserMappingUpsertOne) SetAPIKeyID(v int64) *ExternalUserMappingUpsertOne {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ExternalUserMappingUpsertOne) UpdateAPIKeyID() *ExternalUserMappingUpsertOne {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetUsernameSnapshot sets the "username_snapshot" field.
func (u *ExternalUserMappingUpsertOne) SetUsernameSnapshot(v string) *ExternalUserMappingUpsertOne {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.SetUsernameSnapshot(v)
	})
}

// UpdateUsernameSnapshot sets the "username_snapshot" field to the value that was provided on create.
func (u *ExternalUserMappingUpsertOne) UpdateUsernameSnapshot() *ExternalUserMappingUpsertOne {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.UpdateUsernameSnapshot()
	})
}

// Exec executes the query.
func (u *ExternalUserMappingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExternalUserMappingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExternalUserMappingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExternalUserMappingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExternalUserMappingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExternalUserMappingCreateBulk is the builder for creating many ExternalUserMapping entities in bulk.
type ExternalUserMappingCreateBulk struct {
	config
	err      error
	builders []*ExternalUserMappingCreate
	conflict []sql.ConflictOption
}

// Save creates the ExternalUserMapping entities in the database.
func (_c *ExternalUserMappingCreateBulk) Save(ctx context.Context) ([]*ExternalUserMapping, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExternalUserMapping, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExternalUserMappingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExternalUserMappingCreateBulk) SaveX(ctx context.Context) []*ExternalUserMapping {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExternalUserMappingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExternalUserMappingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExternalUserMapping.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExternalUserMappingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ExternalUserMappingCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExternalUserMappingUpsertBulk {
	_c.conflict = opts
	return &ExternalUserMappingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExternalUserMapping.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExternalUserMappingCreateBulk) OnConflictColumns(columns ...string) *ExternalUserMappingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExternalUserMappingUpsertBulk{
		create: _c,
	}
}

// ExternalUserMappingUpsertBulk is the builder for "upsert"-ing
// a bulk of ExternalUserMapping nodes.
type ExternalUserMappingUpsertBulk struct {
	create *ExternalUserMappingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ExternalUserMapping.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ExternalUserMappingUpsertBulk) UpdateNewValues() *ExternalUserMappingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(externalusermapping.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExternalUserMapping.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExternalUserMappingUpsertBulk) Ignore() *ExternalUserMappingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExternalUserMappingUpsertBulk) DoNothing() *ExternalUserMappingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExternalUserMappingCreateBulk.OnConflict
// documentation for more info.
func (u *ExternalUserMappingUpsertBulk) Update(set func(*ExternalUserMappingUpsert)) *ExternalUserMappingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExternalUserMappingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExternalUserMappingUpsertBulk) SetUpdatedAt(v time.Time) *ExternalUserMappingUpsertBulk {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExternalUserMappingUpsertBulk) UpdateUpdatedAt() *ExternalUserMappingUpsertBulk {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ExternalUserMappingUpsertBulk) SetDeletedAt(v time.Time) *ExternalUserMappingUpsertBulk {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ExternalUserMappingUpsertBulk) UpdateDeletedAt() *ExternalUserMappingUpsertBulk {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ExternalUserMappingUpsertBulk) ClearDeletedAt() *ExternalUserMappingUpsertBulk {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.ClearDeletedAt()
	})
}

// SetExternalUserID sets the "external_user_id" field.
func (u *ExternalUserMappingUpsertBulk) SetExternalUserID(v string) *ExternalUserMappingUpsertBulk {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.SetExternalUserID(v)
	})
}

// UpdateExternalUserID sets the "external_user_id" field to the value that was provided on create.
func (u *ExternalUserMappingUpsertBulk) UpdateExternalUserID() *ExternalUserMappingUpsertBulk {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.UpdateExternalUserID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ExternalUserMappingUpsertBulk) SetUserID(v int64) *ExternalUserMappingUpsertBulk {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ExternalUserMappingUpsertBulk) UpdateUserID() *ExternalUserMappingUpsertBulk {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ExternalUserMappingUpsertBulk) SetAPIKeyID(v int64) *ExternalUserMappingUpsertBulk {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ExternalUserMappingUpsertBulk) UpdateAPIKeyID() *ExternalUserMappingUpsertBulk {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetUsernameSnapshot sets the "username_snapshot" field.
func (u *ExternalUserMappingUpsertBulk) SetUsernameSnapshot(v string) *ExternalUserMappingUpsertBulk {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.SetUsernameSnapshot(v)
	})
}

// UpdateUsernameSnapshot sets the "username_snapshot" field to the value that was provided on create.
func (u *ExternalUserMappingUpsertBulk) UpdateUsernameSnapshot() *ExternalUserMappingUpsertBulk {
	return u.Update(func(s *ExternalUserMappingUpsert) {
		s.UpdateUsernameSnapshot()
	})
}

// Exec executes the query.
func (u *ExternalUserMappingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ExternalUserMappingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExternalUserMappingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExternalUserMappingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
