// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/externalusermapping"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ExternalUserMappingDelete is the builder for deleting a ExternalUserMapping entity.
type ExternalUserMappingDelete struct {
	config
	hooks    []Hook
	mutation *ExternalUserMappingMutation
}

// Where appends a list predicates to the ExternalUserMappingDelete builder.
func (_d *ExternalUserMappingDelete) Where(ps ...predicate.ExternalUserMapping) *ExternalUserMappingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ExternalUserMappingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ExternalUserMappingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ExternalUserMappingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(externalusermapping.Table, sqlgraph.NewFieldSpec(externalusermapping.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ExternalUserMappingDeleteOne is the builder for deleting a single ExternalUserMapping entity.
type ExternalUserMappingDeleteOne struct {
	_d *ExternalUserMappingDelete
}

// Where appends a list predicates to the ExternalUserMappingDelete builder.
func (_d *ExternalUserMappingDeleteOne) Where(ps ...predicate.ExternalUserMapping) *ExternalUserMappingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ExternalUserMappingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{externalusermapping.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ExternalUserMappingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
