// Code generated by ent, DO NOT EDIT.

package externalusermapping

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldDeletedAt, v))
}

// ExternalUserID applies equality check predicate on the "external_user_id" field. It's identical to ExternalUserIDEQ.
func ExternalUserID(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldExternalUserID, v))
}

// ExternalOrganizationID applies equality check predicate on the "external_organization_id" field. It's identical to ExternalOrganizationIDEQ.
func ExternalOrganizationID(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldExternalOrganizationID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldAPIKeyID, v))
}

// UsernameSnapshot applies equality check predicate on the "username_snapshot" field. It's identical to UsernameSnapshotEQ.
func UsernameSnapshot(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldUsernameSnapshot, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNotNull(FieldDeletedAt))
}

// ExternalUserIDEQ applies the EQ predicate on the "external_user_id" field.
func ExternalUserIDEQ(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldExternalUserID, v))
}

// ExternalUserIDNEQ applies the NEQ predicate on the "external_user_id" field.
func ExternalUserIDNEQ(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNEQ(FieldExternalUserID, v))
}

// ExternalUserIDIn applies the In predicate on the "external_user_id" field.
func ExternalUserIDIn(vs ...string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldIn(FieldExternalUserID, vs...))
}

// ExternalUserIDNotIn applies the NotIn predicate on the "external_user_id" field.
func ExternalUserIDNotIn(vs ...string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNotIn(FieldExternalUserID, vs...))
}

// ExternalUserIDGT applies the GT predicate on the "external_user_id" field.
func ExternalUserIDGT(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldGT(FieldExternalUserID, v))
}

// ExternalUserIDGTE applies the GTE predicate on the "external_user_id" field.
func ExternalUserIDGTE(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldGTE(FieldExternalUserID, v))
}

// ExternalUserIDLT applies the LT predicate on the "external_user_id" field.
func ExternalUserIDLT(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldLT(FieldExternalUserID, v))
}

// ExternalUserIDLTE applies the LTE predicate on the "external_user_id" field.
func ExternalUserIDLTE(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldLTE(FieldExternalUserID, v))
}

// ExternalUserIDContains applies the Contains predicate on the "external_user_id" field.
func ExternalUserIDContains(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldContains(FieldExternalUserID, v))
}

// ExternalUserIDHasPrefix applies the HasPrefix predicate on the "external_user_id" field.
func ExternalUserIDHasPrefix(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldHasPrefix(FieldExternalUserID, v))
}

// ExternalUserIDHasSuffix applies the HasSuffix predicate on the "external_user_id" field.
func ExternalUserIDHasSuffix(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldHasSuffix(FieldExternalUserID, v))
}

// ExternalUserIDEqualFold applies the EqualFold predicate on the "external_user_id" field.
func ExternalUserIDEqualFold(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEqualFold(FieldExternalUserID, v))
}

// ExternalUserIDContainsFold applies the ContainsFold predicate on the "external_user_id" field.
func ExternalUserIDContainsFold(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldContainsFold(FieldExternalUserID, v))
}

// ExternalOrganizationIDEQ applies the EQ predicate on the "external_organization_id" field.
func ExternalOrganizationIDEQ(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldExternalOrganizationID, v))
}

// ExternalOrganizationIDNEQ applies the NEQ predicate on the "external_organization_id" field.
func ExternalOrganizationIDNEQ(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNEQ(FieldExternalOrganizationID, v))
}

// ExternalOrganizationIDIn applies the In predicate on the "external_organization_id" field.
func ExternalOrganizationIDIn(vs ...string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldIn(FieldExternalOrganizationID, vs...))
}

// ExternalOrganizationIDNotIn applies the NotIn predicate on the "external_organization_id" field.
func ExternalOrganizationIDNotIn(vs ...string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNotIn(FieldExternalOrganizationID, vs...))
}

// ExternalOrganizationIDGT applies the GT predicate on the "external_organization_id" field.
func ExternalOrganizationIDGT(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldGT(FieldExternalOrganizationID, v))
}

// ExternalOrganizationIDGTE applies the GTE predicate on the "external_organization_id" field.
func ExternalOrganizationIDGTE(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldGTE(FieldExternalOrganizationID, v))
}

// ExternalOrganizationIDLT applies the LT predicate on the "external_organization_id" field.
func ExternalOrganizationIDLT(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldLT(FieldExternalOrganizationID, v))
}

// ExternalOrganizationIDLTE applies the LTE predicate on the "external_organization_id" field.
func ExternalOrganizationIDLTE(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldLTE(FieldExternalOrganizationID, v))
}

// ExternalOrganizationIDContains applies the Contains predicate on the "external_organization_id" field.
func ExternalOrganizationIDContains(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldContains(FieldExternalOrganizationID, v))
}

// ExternalOrganizationIDHasPrefix applies the HasPrefix predicate on the "external_organization_id" field.
func ExternalOrganizationIDHasPrefix(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldHasPrefix(FieldExternalOrganizationID, v))
}

// ExternalOrganizationIDHasSuffix applies the HasSuffix predicate on the "external_organization_id" field.
func ExternalOrganizationIDHasSuffix(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldHasSuffix(FieldExternalOrganizationID, v))
}

// ExternalOrganizationIDEqualFold applies the EqualFold predicate on the "external_organization_id" field.
func ExternalOrganizationIDEqualFold(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEqualFold(FieldExternalOrganizationID, v))
}

// ExternalOrganizationIDContainsFold applies the ContainsFold predicate on the "external_organization_id" field.
func ExternalOrganizationIDContainsFold(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldContainsFold(FieldExternalOrganizationID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNotIn(FieldUserID, vs...))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// UsernameSnapshotEQ applies the EQ predicate on the "username_snapshot" field.
func UsernameSnapshotEQ(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEQ(FieldUsernameSnapshot, v))
}

// UsernameSnapshotNEQ applies the NEQ predicate on the "username_snapshot" field.
func UsernameSnapshotNEQ(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNEQ(FieldUsernameSnapshot, v))
}

// UsernameSnapshotIn applies the In predicate on the "username_snapshot" field.
func UsernameSnapshotIn(vs ...string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldIn(FieldUsernameSnapshot, vs...))
}

// UsernameSnapshotNotIn applies the NotIn predicate on the "username_snapshot" field.
func UsernameSnapshotNotIn(vs ...string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldNotIn(FieldUsernameSnapshot, vs...))
}

// UsernameSnapshotGT applies the GT predicate on the "username_snapshot" field.
func UsernameSnapshotGT(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldGT(FieldUsernameSnapshot, v))
}

// UsernameSnapshotGTE applies the GTE predicate on the "username_snapshot" field.
func UsernameSnapshotGTE(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldGTE(FieldUsernameSnapshot, v))
}

// UsernameSnapshotLT applies the LT predicate on the "username_snapshot" field.
func UsernameSnapshotLT(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldLT(FieldUsernameSnapshot, v))
}

// UsernameSnapshotLTE applies the LTE predicate on the "username_snapshot" field.
func UsernameSnapshotLTE(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldLTE(FieldUsernameSnapshot, v))
}

// UsernameSnapshotContains applies the Contains predicate on the "username_snapshot" field.
func UsernameSnapshotContains(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldContains(FieldUsernameSnapshot, v))
}

// UsernameSnapshotHasPrefix applies the HasPrefix predicate on the "username_snapshot" field.
func UsernameSnapshotHasPrefix(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldHasPrefix(FieldUsernameSnapshot, v))
}

// UsernameSnapshotHasSuffix applies the HasSuffix predicate on the "username_snapshot" field.
func UsernameSnapshotHasSuffix(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldHasSuffix(FieldUsernameSnapshot, v))
}

// UsernameSnapshotEqualFold applies the EqualFold predicate on the "username_snapshot" field.
func UsernameSnapshotEqualFold(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldEqualFold(FieldUsernameSnapshot, v))
}

// UsernameSnapshotContainsFold applies the ContainsFold predicate on the "username_snapshot" field.
func UsernameSnapshotContainsFold(v string) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.FieldContainsFold(FieldUsernameSnapshot, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExternalUserMapping) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExternalUserMapping) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExternalUserMapping) predicate.ExternalUserMapping {
	return predicate.ExternalUserMapping(sql.NotPredicates(p))
}
